In [1]:
import torch

In [7]:
rand_seed = 1729

In [4]:
z = torch.zeros(5, 3)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [6]:
z_int16 = torch.ones((5, 3), dtype=torch.int16)
print(z_int16)
print(z_int16.dtype)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
torch.int16


In [16]:
torch.manual_seed(rand_seed)
r1 = torch.rand((2, 2))
print(r1)

r2 = torch.rand((2, 2))
print(r2)

torch.manual_seed(rand_seed)
r3 = torch.rand((2, 2))
print(r3)

tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


In [31]:
ones = torch.ones((2, 3))
print(ones)

twos = torch.ones((2, 3)) * 2
print(twos)

threes = ones + twos
print(threes)
print(threes.shape)

r1 = torch.rand((2, 3))
r2 = torch.rand((3, 2))

# Different ways of doing matrix multiplication
print(r1 @ r2)
print(torch.mm(r1, r2))
print(torch.matmul(r1, r2))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.Size([2, 3])
tensor([[0.9143, 1.3508],
        [0.3093, 0.5889]])
tensor([[0.9143, 1.3508],
        [0.3093, 0.5889]])
tensor([[0.9143, 1.3508],
        [0.3093, 0.5889]])


In [71]:
r = ((torch.rand((2, 2)) - 0.5) * 2)
print(r)

print(
    torch.abs(r)
)

print(
    torch.asin(r)
)

print(
    torch.det(r)
)

print(
    torch.svd(r)
)

print(
    torch.std_mean(r)
)

print(
    torch.mean(r)
)

print(
    torch.std(r)
)

print(
    torch.max(r)
)

tensor([[ 0.8577,  0.2585],
        [ 0.2528, -0.0593]])
tensor([[0.8577, 0.2585],
        [0.2528, 0.0593]])
tensor([[ 1.0308,  0.2615],
        [ 0.2555, -0.0593]])
tensor(-0.1162)
torch.return_types.svd(
U=tensor([[-0.9687, -0.2481],
        [-0.2481,  0.9687]]),
S=tensor([0.9242, 0.1257]),
V=tensor([[-0.9669,  0.2551],
        [-0.2551, -0.9669]]))
(tensor(0.3834), tensor(0.3274))
tensor(0.3274)
tensor(0.3834)
tensor(0.8577)
