In [28]:
import torch
import numpy as np

In [29]:
torch.manual_seed(945673)

In [30]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)
print(x_data.dtype)

tensor([[1, 2],
        [3, 4]])
torch.int64


In [31]:
np_array = np.array(data)
print(np_array)
x_np = torch.from_numpy(np_array)
print(x_np)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


In [32]:
x_ones = torch.ones_like(x_data)
print(x_ones)
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.6091, 0.3262],
        [0.6054, 0.0556]])


In [33]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
print(rand_tensor)
ones_tensor = torch.ones(shape)
print(ones_tensor)
zeros_tensor = torch.zeros(shape)
print(zeros_tensor)

tensor([[0.4611, 0.6640, 0.6787],
        [0.4764, 0.6888, 0.8816]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [34]:
tensor = torch.rand((3, 4))
print(tensor)
print(tensor.shape)
print(tensor.size())
print(tensor.dtype)
print(tensor.device)
if torch.cuda.is_available():
    tensor = tensor.to(torch.device("cuda:0"))
print(tensor.device)
tensor = tensor.to(torch.device("cpu"))
print(tensor.device)

tensor([[0.6797, 0.8945, 0.7646, 0.3660],
        [0.1215, 0.5605, 0.2480, 0.6530],
        [0.1058, 0.9521, 0.4973, 0.8450]])
torch.Size([3, 4])
torch.Size([3, 4])
torch.float32
cpu
cuda:0
cpu


In [58]:
torch.manual_seed(945673)
tensor = torch.rand((4, 4))
print(tensor)
print(tensor[0])
# Keep dimensions
print(tensor[0:1])
# ... = handle as many previous dimensions as there are
# E.g., [:, :, ..., :, 1]
print(tensor[...,0])
# Keep dimensions
print(tensor[...,0:1])
print(tensor[:,-1][..., None])

tensor([[0.6091, 0.3262, 0.6054, 0.0556],
        [0.4611, 0.6640, 0.6787, 0.4764],
        [0.6888, 0.8816, 0.6797, 0.8945],
        [0.7646, 0.3660, 0.1215, 0.5605]])
tensor([0.6091, 0.3262, 0.6054, 0.0556])
tensor([[0.6091, 0.3262, 0.6054, 0.0556]])
tensor([0.6091, 0.4611, 0.6888, 0.7646])
tensor([[0.6091],
        [0.4611],
        [0.6888],
        [0.7646]])
tensor([[0.0556],
        [0.4764],
        [0.8945],
        [0.5605]])


In [64]:
cat_tensor = torch.cat([tensor, tensor * 2], dim=1)
print(cat_tensor)
stack_tensor = torch.stack([tensor, tensor * 2], dim=0)
print(stack_tensor)

tensor([[0.6091, 0.3262, 0.6054, 0.0556, 1.2183, 0.6524, 1.2107, 0.1112],
        [0.4611, 0.6640, 0.6787, 0.4764, 0.9221, 1.3279, 1.3575, 0.9528],
        [0.6888, 0.8816, 0.6797, 0.8945, 1.3777, 1.7632, 1.3595, 1.7890],
        [0.7646, 0.3660, 0.1215, 0.5605, 1.5291, 0.7319, 0.2430, 1.1211]])
tensor([[[0.6091, 0.3262, 0.6054, 0.0556],
         [0.4611, 0.6640, 0.6787, 0.4764],
         [0.6888, 0.8816, 0.6797, 0.8945],
         [0.7646, 0.3660, 0.1215, 0.5605]],

        [[1.2183, 0.6524, 1.2107, 0.1112],
         [0.9221, 1.3279, 1.3575, 0.9528],
         [1.3777, 1.7632, 1.3595, 1.7890],
         [1.5291, 0.7319, 0.2430, 1.1211]]])
