In [1]:
import torch
import numpy as np

In [2]:
torch.manual_seed(945673)

In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)
print(x_data.dtype)

tensor([[1, 2],
        [3, 4]])
torch.int64


In [4]:
np_array = np.array(data)
print(np_array)
x_np = torch.from_numpy(np_array)
print(x_np)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


In [5]:
x_ones = torch.ones_like(x_data)
print(x_ones)
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.6091, 0.3262],
        [0.6054, 0.0556]])


In [6]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
print(rand_tensor)
ones_tensor = torch.ones(shape)
print(ones_tensor)
zeros_tensor = torch.zeros(shape)
print(zeros_tensor)

tensor([[0.4611, 0.6640, 0.6787],
        [0.4764, 0.6888, 0.8816]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
tensor = torch.rand((3, 4))
print(tensor)
print(tensor.shape)
print(tensor.size())
print(tensor.dtype)
print(tensor.device)
if torch.cuda.is_available():
    tensor = tensor.to(torch.device("cuda:0"))
print(tensor.device)
tensor = tensor.to(torch.device("cpu"))
print(tensor.device)

tensor([[0.6797, 0.8945, 0.7646, 0.3660],
        [0.1215, 0.5605, 0.2480, 0.6530],
        [0.1058, 0.9521, 0.4973, 0.8450]])
torch.Size([3, 4])
torch.Size([3, 4])
torch.float32
cpu
cuda:0
cpu


In [8]:
torch.manual_seed(945673)
tensor = torch.rand((4, 4))
print(tensor)
print(tensor[0])
# Keep dimensions
print(tensor[0:1])
# ... = handle as many previous dimensions as there are
# E.g., [:, :, ..., :, 1]
print(tensor[...,0])
# Keep dimensions
print(tensor[...,0:1])
print(tensor[:,-1][..., None])

tensor([[0.6091, 0.3262, 0.6054, 0.0556],
        [0.4611, 0.6640, 0.6787, 0.4764],
        [0.6888, 0.8816, 0.6797, 0.8945],
        [0.7646, 0.3660, 0.1215, 0.5605]])
tensor([0.6091, 0.3262, 0.6054, 0.0556])
tensor([[0.6091, 0.3262, 0.6054, 0.0556]])
tensor([0.6091, 0.4611, 0.6888, 0.7646])
tensor([[0.6091],
        [0.4611],
        [0.6888],
        [0.7646]])
tensor([[0.0556],
        [0.4764],
        [0.8945],
        [0.5605]])


In [9]:
cat_tensor = torch.cat([tensor, tensor * 2], dim=1)
print(cat_tensor)
stack_tensor = torch.stack([tensor, tensor * 2], dim=0)
print(stack_tensor)

tensor([[0.6091, 0.3262, 0.6054, 0.0556, 1.2183, 0.6524, 1.2107, 0.1112],
        [0.4611, 0.6640, 0.6787, 0.4764, 0.9221, 1.3279, 1.3575, 0.9528],
        [0.6888, 0.8816, 0.6797, 0.8945, 1.3777, 1.7632, 1.3595, 1.7890],
        [0.7646, 0.3660, 0.1215, 0.5605, 1.5291, 0.7319, 0.2430, 1.1211]])
tensor([[[0.6091, 0.3262, 0.6054, 0.0556],
         [0.4611, 0.6640, 0.6787, 0.4764],
         [0.6888, 0.8816, 0.6797, 0.8945],
         [0.7646, 0.3660, 0.1215, 0.5605]],

        [[1.2183, 0.6524, 1.2107, 0.1112],
         [0.9221, 1.3279, 1.3575, 0.9528],
         [1.3777, 1.7632, 1.3595, 1.7890],
         [1.5291, 0.7319, 0.2430, 1.1211]]])


In [13]:
y1 = tensor @ tensor.T
print(y1)
y2 = tensor.matmul(tensor.T)
print(y2)
y3 = torch.zeros_like(y1)
torch.matmul(tensor, tensor.T, out=y3)
print(y3)

z1 = tensor * tensor
print(z1)
z2 = tensor.mul(tensor)
print(z2)

z3 = torch.zeros_like(z1)
torch.mul(tensor, tensor, out=z3)
print(z3)

tensor([[0.8470, 0.9348, 1.1684, 0.6898],
        [0.9348, 1.3411, 1.7905, 0.9450],
        [1.1684, 1.7905, 2.5139, 1.4333],
        [0.6898, 0.9450, 1.4333, 1.0475]])
tensor([[0.8470, 0.9348, 1.1684, 0.6898],
        [0.9348, 1.3411, 1.7905, 0.9450],
        [1.1684, 1.7905, 2.5139, 1.4333],
        [0.6898, 0.9450, 1.4333, 1.0475]])
tensor([[0.8470, 0.9348, 1.1684, 0.6898],
        [0.9348, 1.3411, 1.7905, 0.9450],
        [1.1684, 1.7905, 2.5139, 1.4333],
        [0.6898, 0.9450, 1.4333, 1.0475]])
tensor([[0.3710, 0.1064, 0.3665, 0.0031],
        [0.2126, 0.4409, 0.4607, 0.2270],
        [0.4745, 0.7772, 0.4620, 0.8001],
        [0.5846, 0.1339, 0.0148, 0.3142]])
tensor([[0.3710, 0.1064, 0.3665, 0.0031],
        [0.2126, 0.4409, 0.4607, 0.2270],
        [0.4745, 0.7772, 0.4620, 0.8001],
        [0.5846, 0.1339, 0.0148, 0.3142]])
tensor([[0.3710, 0.1064, 0.3665, 0.0031],
        [0.2126, 0.4409, 0.4607, 0.2270],
        [0.4745, 0.7772, 0.4620, 0.8001],
        [0.5846, 0.1339, 0.01

In [18]:
agg = tensor.sum()
print(agg)
agg_item = agg.item()
print(agg_item)
print(type(agg_item))

tensor(8.8337)
8.833694458007812
<class 'float'>


In [20]:
tensor_copy = torch.clone(tensor)
print(tensor_copy)
tensor_copy.add_(5)
print(tensor_copy)

tensor([[0.6091, 0.3262, 0.6054, 0.0556],
        [0.4611, 0.6640, 0.6787, 0.4764],
        [0.6888, 0.8816, 0.6797, 0.8945],
        [0.7646, 0.3660, 0.1215, 0.5605]])
tensor([[5.6091, 5.3262, 5.6054, 5.0556],
        [5.4611, 5.6640, 5.6787, 5.4764],
        [5.6888, 5.8816, 5.6797, 5.8945],
        [5.7646, 5.3660, 5.1215, 5.5605]])


In [23]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)

t.add_(1)
print(t)
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [25]:
n2 = np.ones(5)
print(n2)
t2 = torch.from_numpy(n2)
print(t2)
np.add(n2, 1, out=n2)
print(n2)
print(t2)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
